name: "Teams Notifications"
description: "Send messages to a teams channel by means of an incoming webhook"

inputs:
  webhook_url:
    description: "The Microsoft Teams Incoming Webhook URL"
    required: true
  message:
    description: "The message to send to Microsoft Teams"
    required: true
  status:
    description: "The status of the message; expect values from needs.<job_id>.result"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
